In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf
from scipy import stats
from itertools import combinations

/home/mtmoncur/.local/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

In [2]:
teams_abbr = {'- - -': '- - -', 'ANA': 'Angels', 'ARI': 'Diamondbacks', 
 'ATL': 'Braves', 'BAL': 'Orioles', 'BOS': 'Red Sox', 'CHC': 'Cubs', 
 'CHW': 'White Sox', 'CIN': 'Reds', 'CLE': 'Indians', 'COL': 'Rockies',
 'DET': 'Tigers', 'FLA': 'Marlins', 'HOU': 'Astros', 'KCR': 'Royals', 
 'LAA': 'Angels', 'LAD': 'Dodgers', 'MIA': 'Marlins', 'MIL': 'Brewers',
 'MIN': 'Twins', 'MON': 'Expos', 'NYM': 'Mets', 'NYY': 'Yankees',
 'OAK': 'Athletics', 'PHI': 'Phillies', 'PIT': 'Pirates', 'SDP': 'Padres',
 'SEA': 'Mariners', 'SFG': 'Giants', 'STL': 'Cardinals', 'TBD': 'Devil Rays', 
 'TBR': 'Rays', 'TEX': 'Rangers', 'TOR': 'Blue Jays', 'WSN': 'Nationals'}

In [3]:
#read in all data
sp = pd.read_csv('FanGraphs_Starters (2).csv')
rp = pd.read_csv('FanGraphs_Relievers (2).csv')
fd = pd.read_csv('FanGraphs_Fielders (2).csv')
bt = pd.read_csv('FanGraphs_Batting (2).csv')

a, b, c = len(sp),len(rp),len(fd)
print("""Number of starter pitchers:\t{}
Number of relief pitchers:\t{}
Number of fielders:\t\t{}
-------------------------------------
Total number of records:\t{}""".format(a, b, c, a+b+c))

#change abbreviation to full team name
fd.loc[[True]*len(fd),'Team'] = [teams_abbr[k] for k in fd.Team]

Number of starter pitchers:	2741
Number of relief pitchers:	1265
Number of fielders:		16122
-------------------------------------
Total number of records:	20128

In [4]:
bt.columns

Index(['Season', 'Name', 'Team', 'G', 'PA', 'HR', 'R', 'RBI', 'SB', 'BB%',
       'K%', 'ISO', 'BABIP', 'AVG', 'OBP', 'SLG', 'wOBA', 'wRC+', 'BsR', 'Off',
       'Def', 'WAR', 'playerid'],
      dtype='object')

In [5]:
rp.columns

Index(['Season', 'Name', 'Team', 'W', 'L', 'SV', 'G', 'GS', 'IP', 'K/9',
       'BB/9', 'HR/9', 'BABIP', 'LOB%', 'GB%', 'HR/FB', 'ERA', 'FIP', 'xFIP',
       'WAR', 'playerid'],
      dtype='object')

In [6]:
sp.columns

Index(['Season', 'Name', 'Team', 'W', 'L', 'SV', 'G', 'GS', 'IP', 'K/9',
       'BB/9', 'HR/9', 'BABIP', 'LOB%', 'GB%', 'HR/FB', 'ERA', 'FIP', 'xFIP',
       'WAR', 'playerid'],
      dtype='object')

In [7]:
print(fd.columns)
fd.sample(5)

Index(['Season', 'Name', 'Team', 'Pos', 'Inn', 'rSB', 'rGDP', 'rARM', 'rGFP',
       'rPM', 'DRS', 'BIZ', 'Plays', 'RZR', 'OOZ', 'CPP', 'RPP', 'TZL', 'FSR',
       'ARM', 'DPR', 'RngR', 'ErrR', 'UZR', 'UZR/150', 'Def', 'playerid'],
      dtype='object')

,Season,Name,Team,Pos,Inn,rSB,rGDP,rARM,rGFP,rPM,...,TZL,FSR,ARM,DPR,RngR,ErrR,UZR,UZR/150,Def,playerid
2069,2004,Juan Uribe,White Sox,2B,625.2,NaN,1.0,NaN,-1,0.0,...,NaN,NaN,NaN,-0.6,2.8,0.6,2.8,6.6,3.9,454
8880,2005,Frank Catalanotto,Blue Jays,LF,761.0,NaN,NaN,5.0,0,-3.0,...,NaN,NaN,0.8,NaN,-0.3,1.0,1.5,3.2,-2.4,1241
4688,2011,Jack Wilson,Mariners,SS,112.2,NaN,0.0,NaN,-1,0.0,...,NaN,1.0,NaN,0.2,-0.9,0.9,0.2,1.3,0.8,1017
7910,2014,Alex Presley,Astros,LF,263.1,NaN,NaN,-1.0,0,1.0,...,NaN,0.0,-0.7,NaN,0.4,0.2,-0.1,1.5,-1.4,5305
11916,2002,Todd Ritchie,White Sox,P,133.2,0.0,NaN,NaN,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,253

In [8]:
#create a 3 sets containing tuples of playerids with the season for each record
fd_season_id = set([tuple(row) for row in fd[['playerid','Season']].values])
rp_season_id = set([tuple(row) for row in rp[['playerid','Season']].values])
sp_season_id = set([tuple(row) for row in sp[['playerid','Season']].values])
bt_season_id = set([tuple(row) for row in bt[['playerid','Season']].values])

a, b, c = len(sp_season_id), len(rp_season_id), len(fd_season_id)
total = set()
total.update(sp_season_id);total.update(rp_season_id);total.update(fd_season_id)

print("Only counting players once per season.\n")
print("""Number of starter pitchers:\t{}
Number of relief pitchers:\t{}
Number of fielders:\t\t{}
-------------------------------------
Total number of records:\t{}""".format(a, b, c, len(total)))

Only counting players once per season.

Number of starter pitchers:	2675
Number of relief pitchers:	1265
Number of fielders:		12253
-------------------------------------
Total number of records:	12254

In [9]:
print(len(bt_season_id.intersection(fd_season_id)))
print(len(bt_season_id.intersection(rp_season_id)))
print(len(bt_season_id.intersection(sp_season_id)))
print(len(rp_season_id.intersection(fd_season_id)))
print(len(rp_season_id.intersection(sp_season_id)))
print(len(sp_season_id.intersection(fd_season_id)))

8157
0
590
1264
3
2675

In [10]:
#create temporary Seasonid column
fd.insert(2,'Seasonid',[tuple(row) for row in fd[['playerid','Season']].values])
rp.insert(2,'Seasonid',[tuple(row) for row in rp[['playerid','Season']].values])
sp.insert(2,'Seasonid',[tuple(row) for row in sp[['playerid','Season']].values])

#find and remove duplicates between dataframes
#mask = fd.Seasonid.isin(sp_season_id)
#fd.drop(fd[mask].index,inplace=True)

#mask = fd.Seasonid.isin(rp_season_id)
#fd.drop(fd[mask].index,inplace=True)

mask = rp.Seasonid.isin(sp_season_id)
rp.drop(rp[mask].index,inplace=True)

#remove temporary Seasonid column
fd.drop('Seasonid',axis=1,inplace=True)
sp.drop('Seasonid',axis=1,inplace=True)
rp.drop('Seasonid',axis=1,inplace=True)

In [11]:
#change all fielder positions (except catcher) to FD
fd.loc[fd.Pos.isin(['1B','2B','3B','RF','LF','CF','SS']),'Pos'] = 'FD'

#add column with potision to prepare for combining data
sp.insert(2, 'Pos', 'P')
rp.insert(2,'Pos', 'P')

In [12]:
p = pd.concat([sp,rp,fd], ignore_index=True)
#p = pd.merge(sp,rp, on=['Season', 'Name']'Seasonid', how='outer')
#p = pd.merge(p, fd, on='Seasonid', how='outer')
p.drop(p[p.Season<2002].index,inplace=True)
p.reset_index()

p.sample(5)

,ARM,BABIP,BB/9,BIZ,CPP,DPR,DRS,Def,ERA,ErrR,...,UZR/150,W,WAR,playerid,rARM,rGDP,rGFP,rPM,rSB,xFIP
280,NaN,0.308,2.49,NaN,NaN,NaN,NaN,NaN,3.47,NaN,...,NaN,13.0,4.2,1943,NaN,NaN,NaN,NaN,NaN,3.71
17003,NaN,NaN,NaN,NaN,NaN,NaN,-3.0,NaN,NaN,NaN,...,NaN,NaN,NaN,715,NaN,NaN,0.0,-5.0,2.0,NaN
18284,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,790,NaN,NaN,0.0,2.0,-1.0,NaN
10088,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,-0.2,NaN,NaN,...,NaN,NaN,NaN,1698,NaN,NaN,0.0,NaN,-1.0,NaN
18746,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,8855,NaN,NaN,0.0,1.0,0.0,NaN

In [13]:
p = p.drop(['rSB', 'rGDP', 'rARM', 'rGFP',
       'rPM', 'DRS', 'BIZ', 'Plays', 'RZR', 'OOZ', 'CPP', 'RPP', 'TZL', 'FSR',
       'ARM', 'DPR', 'RngR', 'ErrR', 'UZR', 'UZR/150', 'Def',
        'L', 'SV', 'G', 'GS', 'IP', 'K/9',
       'BB/9', 'HR/9', 'BABIP', 'LOB%', 'GB%', 'HR/FB', 'ERA', 'FIP', 'xFIP',
       ], axis=1)

In [14]:
p['Inn'].fillna(p['Inn'].mean(), inplace=True)
p['WAR'].fillna(p['WAR'].mean(), inplace=True)
p['W'].fillna(p['W'].mean(), inplace=True)

In [15]:
by_pos = p.groupby('Pos')
for g in by_pos.groups:
    group = by_pos.get_group(g)
    print('#'*50)
    print(g)
    for c in p.columns:
        print(c,'\t', len(group)-group[c].count())

##################################################
FD
Inn 	 0
Name 	 0
Pos 	 0
Season 	 0
Team 	 0
W 	 0
WAR 	 0
playerid 	 0
##################################################
P
Inn 	 0
Name 	 0
Pos 	 0
Season 	 0
Team 	 0
W 	 0
WAR 	 0
playerid 	 0
##################################################
C
Inn 	 0
Name 	 0
Pos 	 0
Season 	 0
Team 	 0
W 	 0
WAR 	 0
playerid 	 0

In [16]:
#account for team name changes
p.loc[p.Team=='Devil Rays','Team'] = 'Rays'
p.loc[p.Team=='Expos','Team'] = 'Nationals'
del(teams_abbr['MON'])
del(teams_abbr['TBD'])

#delete players from a season if their team is unknown
p.drop(p[p.Team=='- - -'].index,inplace=True)
del(teams_abbr['- - -'])

In [18]:
print("Number of records before:\t{}".format(len(p)))
p.drop_duplicates(inplace=True)
print("Number of records after:\t{}".format(len(p)))

Number of records before:	20122
Number of records after:	20122

In [19]:
p.sample(5)

,Inn,Name,Pos,Season,Team,W,WAR,playerid
3838,364.8328,D.J. Carrasco,P,2003,Royals,6.000000,0.000000,1666
4903,1277.2000,Carlos Lee,FD,2004,White Sox,7.436672,1.598176,243
19135,149.1000,Danny Duffy,P,2014,Royals,7.436672,1.598176,3542
12527,423.0000,David Dahl,FD,2016,Rockies,7.436672,1.598176,13744
6264,799.2000,Dustin Pedroia,FD,2015,Red Sox,7.436672,1.598176,8370

In [20]:
p.dropna(axis=1, how='any')

,Inn,Name,Pos,Season,Team,W,WAR,playerid
0,364.8328,Randy Johnson,P,2004,Diamondbacks,16.000000,9.600000,60
1,364.8328,Curt Schilling,P,2002,Diamondbacks,23.000000,9.400000,73
2,364.8328,Zack Greinke,P,2009,Royals,16.000000,8.600000,1943
3,364.8328,Clayton Kershaw,P,2015,Dodgers,16.000000,8.500000,2036
4,364.8328,Roy Halladay,P,2011,Phillies,19.000000,8.300000,1303
5,364.8328,Randy Johnson,P,2002,Diamondbacks,24.000000,8.100000,60
6,364.8328,Ben Sheets,P,2004,Brewers,12.000000,8.000000,710
7,364.8328,Mark Prior,P,2003,Cubs,18.000000,7.800000,301
8,364.8328,Justin Verlander,P,2009,Tigers,19.000000,7.700000,8700
9,364.8328,Tim Lincecum,P,2009,Giants,15.000000,7.700000,5705
10,364.8328,Chris Sale,P,2017,Red Sox,17.000000,7.700000,10603
11,364.8328,Clayton Kershaw,P,2014,Dodgers,21.000000,7.600000,2036
12,364.8328,Pedro Martinez,P,2003,Red Sox,14.000000,7.400000,200
13,364.8328,Pedro Martinez,P,2002,Red Sox,20.000000,7.400000,200
14,364.8328,Corey Kluber,P,2014,Indians,18.000000,7.400000,2429
15,364.8328,Jake Arrieta,P,2015,Cubs,22.000000,7.300000,4153
16,364.8328,Corey Kluber,P,2017,Indians,18.000000,7.300000,2429
17,364.8328,Tim Lincecum,P,2008,Giants,17.000000,7.100000,5705
18,364.8328,Clayton Kershaw,P,2011,Dodgers,21.000000,7.100000,2036
19,364.8328,Clayton Kershaw,P,2013,Dodgers,16.000000,7.100000,2036
20,364.8328,Johan Santana,P,2005,Twins,16.000000,7.100000,755
21,364.8328,Roy Halladay,P,2003,Blue Jays,22.000000,7.000000,1303
22,364.8328,Roy Halladay,P,2009,Blue Jays,17.000000,7.000000,1303
23,364.8328,Esteban Loaiza,P,2003,White Sox,21.000000,6.900000,1310
24,364.8328,Justin Verlander,P,2012,Tigers,17.000000,6.800000,8700
25,364.8328,Roy Halladay,P,2002,Blue Jays,19.000000,6.800000,1303
26,364.8328,Johan Santana,P,2004,Twins,20.000000,6.800000,755
27,364.8328,Cliff Lee,P,2011,Phillies,17.000000,6.800000,1636
28,364.8328,Johan Santana,P,2006,Twins,19.000000,6.700000,755
29,364.8328,Cliff Lee,P,2008,Indians,22.000000,6.700000,1636
...,...,...,...,...,...,...,...,...
20095,88.2000,Ben Lively,P,2017,Phillies,7.436672,1.598176,14932
20096,68.1000,Jose Torres,P,2017,Padres,7.436672,1.598176,14957
20097,157.1000,Chad Kuhl,P,2017,Pirates,7.436672,1.598176,14975
20098,76.0000,Corey Knebel,P,2017,Brewers,7.436672,1.598176,15010
20099,162.0000,German Marquez,P,2017,Rockies,7.436672,1.598176,15038
20100,83.0000,Austin Pruitt,P,2017,Rays,7.436672,1.598176,15290
20101,135.0000,Matt Boyd,P,2017,Tigers,7.436672,1.598176,15440
20102,133.0000,Nick Pivetta,P,2017,Phillies,7.436672,1.598176,15454
20103,134.2000,Antonio Senzatela,P,2017,Rockies,7.436672,1.598176,15488
20104,105.1000,Kendall Graveman,P,2017,Athletics,7.436672,1.598176,15514
20105,90.2000,Mark Leiter,P,2017,Phillies,7.436672,1.598176,15551
20106,69.0000,Chad Green,P,2017,Yankees,7.436672,1.598176,15552
20107,66.1000,Miguel Castro,P,2017,Orioles,7.436672,1.598176,15684
20108,89.1000,Luis Castillo,P,2017,Reds,7.436672,1.598176,15689
20109,178.1000,Masahiro Tanaka,P,2017,Yankees,7.436672,1.598176,15764
20110,158.2000,Sean Manaea,P,2017,Athletics,7.436672,1.598176,15873
20111,193.1000,Luis Severino,P,2017,Yankees,7.436672,1.598176,15890
20112,69.1000,Carlos Rodon,P,2017,White Sox,7.436672,1.598176,16137
20113,168.0000,Aaron Nola,P,2017,Phillies,7.436672,1.598176,16149
20114,91.1000,Daniel Gossett,P,2017,Athletics,7.436672,1.598176,16164
20115,156.0000,Kyle Freeland,P,2017,Rockies,7.436672,1.598176,16256
20116,155.1000,Jordan Montgomery,P,2017,Yankees,7.436672,1.598176,16511
20117,60.1000,Luke Weaver,P,2017,Cardinals,7.436672,1.598176,16918
20118,100.0000,Sean Newcomb,P,2017,Braves,7.436672,1.598176,16943
20119,150.1000,Trevor Williams,P,2017,Pirates,7.436672,1.598176,16977
20120,76.0000,Raisel Iglesias,P,2017,Reds,7.436672,1.598176,17130
20121,114.1000,Dinelson Lamet,P,2017,Padres,7.436672,1.598176,17186
20122,99.1000,Jeff Hoffman,P,2017,Rockies,7.436672,1.598176,17432
20123,160.0000,Ariel Miranda,P,2017,Mariners,7.436672,1.598176,17526
20124,134.1000,Kenta Maeda,P,2017,Dodgers,7.436672,1.598176,18498

In [21]:
if 'Change_Type' in p.columns:
    p.drop('Change_Type', axis=1, inplace=True)
    
    
#initialize the new column with value 'No Change'
p.insert(1, 'Change_Type', 'No Change')
by_player = p.groupby('playerid')

#loop through, player by player
for g in by_player.groups:
    one_p = by_player.get_group(g)
    
    #loop through the years for each player
    for y in sorted(one_p['Season'])[1:]:
        
        #Case: no change
        if sum(one_p.Season==y-1)==0: continue
        
        #Case: arrive
        if (one_p[one_p.Season==y].Team.values[0] != 
        one_p[one_p.Season==y-1].Team.values[0]):
            
            #Case: arrive and previous arrive/leave
            if (p[(p.Season==y-1)&(p.playerid==g)]['Change_Type'].values[0]
            == 'Arrive'):
                p.loc[one_p[one_p.Season==y-1].index,'Change_Type'] = 'Arrive Leave'
                p.loc[one_p[one_p.Season==y].index,'Change_Type'] = 'Arrive'
            
            #Case: arrive and previous leave
            else:
                p.loc[one_p[one_p.Season==y-1].index,'Change_Type'] = 'Leave'
                p.loc[one_p[one_p.Season==y].index,'Change_Type'] = 'Arrive'