In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf
from scipy import stats
from itertools import combinations

C:\Users\Tyler Moncur\Anaconda3\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

In [2]:
teams_abbr = {'- - -': '- - -', 'ANA': 'Angels', 'ARI': 'Diamondbacks', 
 'ATL': 'Braves', 'BAL': 'Orioles', 'BOS': 'Red Sox', 'CHC': 'Cubs', 
 'CHW': 'White Sox', 'CIN': 'Reds', 'CLE': 'Indians', 'COL': 'Rockies',
 'DET': 'Tigers', 'FLA': 'Marlins', 'HOU': 'Astros', 'KCR': 'Royals', 
 'LAA': 'Angels', 'LAD': 'Dodgers', 'MIA': 'Marlins', 'MIL': 'Brewers',
 'MIN': 'Twins', 'MON': 'Expos', 'NYM': 'Mets', 'NYY': 'Yankees',
 'OAK': 'Athletics', 'PHI': 'Phillies', 'PIT': 'Pirates', 'SDP': 'Padres',
 'SEA': 'Mariners', 'SFG': 'Giants', 'STL': 'Cardinals', 'TBD': 'Devil Rays', 
 'TBR': 'Rays', 'TEX': 'Rangers', 'TOR': 'Blue Jays', 'WSN': 'Nationals'}

In [3]:
#read in all data
sp = pd.read_csv('FanGraphs_Starters (2).csv')
rp = pd.read_csv('FanGraphs_Relievers (2).csv')
fd = pd.read_csv('FanGraphs_Fielders (2).csv')

a, b, c = len(sp),len(rp),len(fd)
print("""Number of starter pitchers:\t{}
Number of relief pitchers:\t{}
Number of fielders:\t\t{}
-------------------------------------
Total number of records:\t{}""".format(a, b, c, a+b+c))

#change abbreviation to full team name
fd.loc[[True]*len(fd),'Team'] = [teams_abbr[k] for k in fd.Team]

Number of starter pitchers:	2741
Number of relief pitchers:	1265
Number of fielders:		16122
-------------------------------------
Total number of records:	20128

In [4]:
rp.sample(5)

,Season,Name,Team,W,L,SV,G,GS,IP,K/9,...,HR/9,BABIP,LOB%,GB%,HR/FB,ERA,FIP,xFIP,WAR,playerid
606,2005,Ryan Madson,Phillies,6,5,0,78,0,87.0,8.17,...,1.14,0.299,71.3 %,47.8 %,16.4 %,4.14,3.92,3.34,0.8,1852
21,2014,Wade Davis,Royals,9,2,3,71,0,72.0,13.63,...,0.00,0.264,87.5 %,47.6 %,0.0 %,1.00,1.19,1.93,3.1,7441
245,2005,Scott Eyre,Giants,2,2,0,86,0,68.1,8.56,...,0.40,0.251,77.2 %,36.4 %,4.0 %,2.63,3.01,3.95,1.5,1300
600,2004,Esteban Yan,Tigers,3,6,7,69,0,87.0,7.14,...,0.83,0.316,72.8 %,51.9 %,10.0 %,3.83,3.90,4.01,0.8,1236
997,2013,Cesar Ramos,Rays,2,2,1,48,0,67.1,7.08,...,0.80,0.293,72.3 %,40.9 %,8.2 %,4.14,3.70,4.02,0.2,3357

In [5]:
sp.sample(5)

,Season,Name,Team,W,L,SV,G,GS,IP,K/9,...,HR/9,BABIP,LOB%,GB%,HR/FB,ERA,FIP,xFIP,WAR,playerid
1920,2007,Rodrigo Lopez,Rockies,5,4,0,14,14,79.1,4.88,...,1.25,0.279,68.9 %,47.1 %,10.6 %,4.42,4.75,4.59,0.9,150
2280,2013,Luis Mendoza,Royals,2,5,0,15,15,79.0,5.70,...,0.91,0.306,66.8 %,48.8 %,10.5 %,5.01,4.47,4.46,0.4,3126
2450,2011,Tim Wakefield,Red Sox,7,8,0,23,23,137.1,5.44,...,1.44,0.279,57.9 %,39.0 %,10.6 %,5.31,5.04,4.85,0.2,219
2177,2017,Matt Cain,Giants,3,11,0,23,23,119.1,5.51,...,1.21,0.326,68.0 %,41.8 %,11.4 %,5.05,4.81,5.15,0.6,4732
1190,2008,Greg Maddux,Padres,6,9,0,26,26,153.1,4.70,...,0.94,0.284,66.0 %,49.2 %,10.7 %,3.99,4.05,3.98,1.9,104

In [6]:
fd.sample(5)

,Season,Name,Team,Pos,Inn,rSB,rGDP,rARM,rGFP,rPM,...,TZL,FSR,ARM,DPR,RngR,ErrR,UZR,UZR/150,Def,playerid
12850,2005,Josh Towers,Blue Jays,P,208.2,0.0,NaN,NaN,1,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489
6368,2015,Chris Coghlan,Cubs,2B,78.2,NaN,0.0,NaN,-1,0.0,...,NaN,-1.0,NaN,-0.4,0.3,-0.4,-0.5,-13.2,-0.3,6878
8815,2008,Todd Helton,Rockies,1B,715.1,NaN,0.0,NaN,3,4.0,...,NaN,NaN,NaN,0.3,1.4,2.1,3.8,7.0,-2.3,432
6681,2009,Joe Thurston,Cardinals,3B,463.0,NaN,0.0,NaN,0,1.0,...,NaN,-5.0,NaN,0.2,0.4,-1.9,-1.3,-3.2,-0.5,673
9734,2014,Daniel Murphy,Mets,2B,1140.1,NaN,-3.0,NaN,-1,-6.0,...,NaN,-12.0,NaN,-0.9,-1.6,-3.1,-5.6,-6.2,-3.6,4316

In [7]:
#create a 3 sets containing tuples of playerids with the season for each record
fd_season_id = set([tuple(row) for row in fd[['playerid','Season']].values])
rp_season_id = set([tuple(row) for row in rp[['playerid','Season']].values])
sp_season_id = set([tuple(row) for row in sp[['playerid','Season']].values])

a, b, c = len(sp_season_id), len(rp_season_id), len(fd_season_id)
total = set()
total.update(sp_season_id);total.update(rp_season_id);total.update(fd_season_id)

print("Only counting players once per season.\n")
print("""Number of starter pitchers:\t{}
Number of relief pitchers:\t{}
Number of fielders:\t\t{}
-------------------------------------
Total number of records:\t{}""".format(a, b, c, len(total)))

Only counting players once per season.

Number of starter pitchers:	2675
Number of relief pitchers:	1265
Number of fielders:		12253
-------------------------------------
Total number of records:	12254

In [8]:
#create temporary Seasonid column
fd.insert(2,'Seasonid',[tuple(row) for row in fd[['playerid','Season']].values])
rp.insert(2,'Seasonid',[tuple(row) for row in rp[['playerid','Season']].values])
sp.insert(2,'Seasonid',[tuple(row) for row in sp[['playerid','Season']].values])

#find and remove duplicates between dataframes
mask = fd.Seasonid.isin(sp_season_id)
fd.drop(fd[mask].index,inplace=True)

mask = fd.Seasonid.isin(rp_season_id)
fd.drop(fd[mask].index,inplace=True)

mask = rp.Seasonid.isin(sp_season_id)
rp.drop(rp[mask].index,inplace=True)

#remove temporary Seasonid column
fd.drop('Seasonid',axis=1,inplace=True)
sp.drop('Seasonid',axis=1,inplace=True)
rp.drop('Seasonid',axis=1,inplace=True)

ValueError: Buffer has wrong number of dimensions (expected 1, got 2)

In [9]:
sp_season_id

{(2060, 2005),
 (90, 2008),
 (179, 2002),
 (7410, 2009),
 (16017, 2015),
 (4153, 2010),
 (944, 2006),
 (10185, 2013),
 (3184, 2016),
 (3340, 2013),
 (1051, 2015),
 (560, 2002),
 (7396, 2014),
 (3245, 2008),
 (8678, 2012),
 (1244, 2007),
 (8099, 2007),
 (1137, 2013),
 (3374, 2008),
 (571, 2003),
 (200, 2004),
 (7450, 2015),
 (5221, 2010),
 (105, 2009),
 (2586, 2008),
 (833, 2008),
 (150, 2007),
 (1528, 2002),
 (9303, 2013),
 (790, 2003),
 (2163, 2009),
 (7146, 2011),
 (978, 2012),
 (7448, 2017),
 (10304, 2014),
 (4684, 2006),
 (4424, 2010),
 (1051, 2004),
 (10261, 2011),
 (15514, 2016),
 (2717, 2015),
 (1574, 2005),
 (287, 2006),
 (8678, 2007),
 (5401, 2013),
 (1773, 2007),
 (840, 2007),
 (4640, 2008),
 (4366, 2008),
 (11682, 2017),
 (7059, 2008),
 (1094, 2008),
 (512, 2014),
 (978, 2007),
 (7982, 2012),
 (375, 2015),
 (430, 2008),
 (989, 2006),
 (1029, 2004),
 (5524, 2012),
 (46, 2004),
 (9083, 2009),
 (1131, 2006),
 (9492, 2013),
 (7738, 2015),
 (503, 2005),
 (517, 2010),
 (6893, 2013),
 (7059, 2017),
 (1094, 2003),
 (512, 2005),
 (60, 2006),
 (375, 2004),
 (6797, 2013),
 (8223, 2009),
 (17526, 2017),
 (329, 2003),
 (5524, 2011),
 (4064, 2010),
 (2036, 2008),
 (2608, 2013),
 (4676, 2011),
 (199, 2009),
 (3273, 2013),
 (232, 2002),
 (1667, 2003),
 (14916, 2017),
 (503, 2002),
 (3284, 2010),
 (4222, 2010),
 (5842, 2011),
 (2233, 2009),
 (1451, 2010),
 (2168, 2006),
 (973, 2004),
 (10547, 2017),
 (1757, 2010),
 (6902, 2015),
 (147, 2003),
 (769, 2010),
 (1056, 2003),
 (1841, 2017),
 (1277, 2006),
 (5843, 2008),
 (1636, 2007),
 (9884, 2010),
 (199, 2006),
 (633, 2006),
 (232, 2009),
 (1516, 2005),
 (1667, 2008),
 (9083, 2007),
 (14078, 2016),
 (3284, 2017),
 (1571, 2005),
 (12768, 2014),
 (10314, 2013),
 (883, 2004),
 (4897, 2009),
 (11189, 2016),
 (1757, 2003),
 (5879, 2012),
 (1636, 2014),
 (982, 2004),
 (1585, 2003),
 (9132, 2016),
 (11176, 2014),
 (10732, 2015),
 (1571, 2010),
 (13125, 2013),
 (4371, 2014),
 (3990, 2014),
 (743, 2004),
 (161, 2006),
 (12917, 2016),
 (1128, 2004),
 (15440, 2017),
 (3830, 2012),
 (7754, 2016),
 (4535, 2011),
 (110, 2007),
 (13183, 2017),
 (7396, 2016),
 (977, 2002),
 (3200, 2012),
 (317, 2003),
 (750, 2003),
 (3777, 2011),
 (15764, 2014),
 (9132, 2015),
 (6435, 2012),
 (10130, 2015),
 (895, 2005),
 (1984, 2011),
 (926, 2004),
 (6244, 2010),
 (4235, 2010),
 (1507, 2002),
 (1767, 2014),
 (921, 2005),
 (6943, 2012),
 (6230, 2011),
 (1437, 2004),
 (424, 2005),
 (4806, 2016),
 (6895, 2015),
 (1091, 2004),
 (4732, 2010),
 (11713, 2016),
 (1989, 2013),
 (2072, 2010),
 (491, 2006),
 (1310, 2006),
 (16980, 2016),
 (460, 2002),
 (4849, 2007),
 (3184, 2009),
 (107, 2002),
 (1507, 2011),
 (7410, 2017),
 (8782, 2013),
 (921, 2014),
 (1181, 2002),
 (10131, 2013),
 (8302, 2017),
 (6570, 2016),
 (3403, 2009),
 (16256, 2017),
 (40, 2008),
 (788, 2006),
 (404, 2015),
 (5705, 2013),
 (964, 2006),
 (8044, 2014),
 (225, 2014),
 (11836, 2015),
 (2351, 2006),
 (219, 2009),
 (7448, 2009),
 (6248, 2012),
 (4141, 2016),
 (5279, 2017),
 (7593, 2011),
 (4886, 2007),
 (9434, 2017),
 (3201, 2010),
 (3886, 2009),
 (1172, 2004),
 (4338, 2011),
 (412, 2006),
 (6397, 2016),
 (34, 2005),
 (976, 2010),
 (367, 2002),
 (9137, 2010),
 (1228, 2006),
 (8044, 2005),
 (642, 2003),
 (225, 2007),
 (4972, 2016),
 (10123, 2015),
 (13164, 2016),
 (8011, 2013),
 (6316, 2015),
 (1163, 2002),
 (1508, 2004),
 (475, 2005),
 (13050, 2016),
 (3193, 2008),
 (4141, 2009),
 (7593, 2012),
 (10603, 2013),
 (1442, 2007),
 (1172, 2003),
 (305, 2007),
 (3254, 2016),
 (594, 2007),
 (1077, 2010),
 (2929, 2013),
 (668, 2005),
 (4972, 2015),
 (10197, 2015),
 (13164, 2015),
 (1931, 2004),
 (1245, 2010),
 (16164, 2017),
 (954, 2002),
 (510, 2011),
 (219, 2007),
 (3642, 2011),
 (3580, 2014),
 (14682, 2017),
 (1217, 2007),
 (1508, 2003),
 (2155, 2015),
 (126, 2007),
 (2036, 2017),
 (6283, 2012),
 (106, 2002),
 (1157, 2010),
 (453, 2005),
 (6570, 2013),
 (8173, 2017),
 (1814, 2004),
 (1703, 2005),
 (1089, 2006),
 (761, 2002),
 (5203, 2011),
 (1234, 2002),
 (4972, 2006),
 (1245, 2003),
 (12808, 2017),
 (1303, 2013),
 (2717, 2017),
 (1841, 2008),
 (1514, 2004),
 (126, 2014),
 (12385, 2016),
 (837, 2007),
 (535, 2008),
 (3196, 2009),
 (4930, 2010),
 (6249, 2010),
 (13074, 2016),
 (3543, 2014),
 (5279, 2012),
 (71, 2004),
 (6329, 2013),
 (104, 2007),
 (10310, 2013),
 (8173, 2010),
 (5535, 2011),
 (9901, 2012),
 (115, 2006),
 (5203, 2016),
 (1701, 2012),
 (755, 2002),
 (6176, 2010),
 (1292, 2011),
 (1695, 2003),
 (962, 2004),
 (1303, 2010),
 (5669, 2011),
 (932, 2005),
 (7080, 2011),
 (6986, 2012),
 (10547, 2014),
 (1943, 2014),
 (434, 2006),
 (8700, 2015),
 (1772, 2009),
 (3455, 2008),
 (1118, 2014),
 (815, 2007),
 (3137, 2010),
 (90, 2007),
 (1292, 2002),
 (4772, 2007),
 (13071, 2013),
 (613, 2004),
 (7466, 2011),
 (12970, 2017),
 (944, 2009),
 (1076, 2002),
 (7441, 2011),
 (1045, 2002),
 (1303, 2003),
 (12905, 2016),
 (8851, 2011),
 (8700, 2006),
 (1943, 2007),
 (9033, 2012),
 (16208, 2016),
 (4505, 2017),
 (1546, 2004),
 (1267, 2006),
 (11754, 2016),
 (4279, 2008),
 (4567, 2009),
 (4635, 2010),
 (801, 2006),
 (2586, 2007),
 (150, 2010),
 (739, 2004),
 (7410, 2015),
 (12703, 2016),
 (4772, 2014),
 (27, 2004),
 (1316, 2002),
 (1051, 2009),
 (9425, 2014),
 (573, 2007),
 (1574, 2008),
 (1039, 2002),
 (13774, 2016),
 (8678, 2010),
 (1244, 2009),
 (5673, 2009),
 (8362, 2014),
 (13143, 2015),
 (4567, 2006),
 (105, 2007),
 (823, 2005),
 (133, 2005),
 (739, 2013),
 (16137, 2015),
 (1116, 2010),
 (2060, 2006),
 (13046, 2014),
 (790, 2009),
 (16017, 2014),
 (944, 2007),
 (4684, 2008),
 (3184, 2017),
 (3340, 2014),
 (1051, 2014),
 (1574, 2003),
 (2651, 2007),
 (1137, 2012),
 (8678, 2013),
 (9388, 2010),
 (571, 2002),
 (3374, 2009),
 (200, 2005),
 (7450, 2012),
 (8362, 2009),
 (1569, 2002),
 (9434, 2014),
 (105, 2008),
 (2586, 2009),
 (823, 2002),
 (3254, 2014),
 (150, 2004),
 (4366, 2006),
 (1528, 2003),
 (2134, 2006),
 (512, 2008),
 (7942, 2016),
 (978, 2013),
 (10304, 2015),
 (4684, 2007),
 (4424, 2011),
 (1051, 2007),
 (15514, 2017),
 (2717, 2014),
 (46, 2002),
 (1137, 2005),
 (3374, 2016),
 (840, 2008),
 (9674, 2014),
 (2568, 2006),
 (4366, 2009),
 (7059, 2011),
 (1094, 2009),
 (444, 2004),
 (512, 2015),
 (710, 2006),
 (13619, 2017),
 (978, 2004),
 (12703, 2015),
 (60, 2008),
 (375, 2014),
 (430, 2009),
 (989, 2005),
 (1029, 2003),
 (5524, 2013),
 (18498, 2016),
 (4676, 2013),
 (3273, 2011),
 (666, 2004),
 (9083, 2008),
 (3292, 2012),
 (1283, 2004),
 (9492, 2014),
 (503, 2004),
 (517, 2009),
 (6893, 2012),
 (3284, 2012),
 (7059, 2016),
 (13125, 2017),
 (2233, 2007),
 (512, 2006),
 (6562, 2014),
 (973, 2010),
 (526, 2008),
 (375, 2007),
 (12638, 2015),
 (329, 2002),
 (4878, 2013),
 (7872, 2012),
 (4064, 2011),
 (2036, 2009),
 (3815, 2016),
 (3688, 2007),
 (2608, 2014),
 (9884, 2012),
 (199, 2008),
 (232, 2003),
 (10811, 2015),
 (3284, 2011),
 (4640, 2007),
 (4662, 2009),
 (5842, 2008),
 (2233, 2008),
 (14120, 2015),
 (1451, 2013),
 (10547, 2016),
 (1757, 2009),
 (2227, 2007),
 (147, 2002),
 (1056, 2004),
 (3855, 2014),
 (1841, 2016),
 (1277, 2005),
 (8779, 2013),
 (1633, 2003),
 (982, 2002),
 (1894, 2007),
 (9884, 2011),
 (633, 2005),
 (1011, 2004),
 (232, 2010),
 (9083, 2006),
 (1516, 2006),
 (14078, 2017),
 (13287, 2017),
 (1571, 2004),
 (2233, 2017),
 (12768, 2015),
 (4253, 2009),
 (1451, 2002),
 (4772, 2016),
 (4897, 2008),
 (10954, 2014),
 (3830, 2010),
 (982, 2005),
 (1633, 2004),
 (8591, 2011),
 (1011, 2013),
 (4776, 2016),
 (11176, 2015),
 (6317, 2011),
 (1195, 2004),
 (926, 2002),
 (3990, 2015),
 (4371, 2017),
 (161, 2005),
 (921, 2003),
 (1128, 2005),
 (12049, 2017),
 (8686, 2008),
 (446, 2006),
 (4535, 2010),
 (3830, 2013),
 (7754, 2017),
 (13183, 2016),
 (3200, 2013),
 (317, 2002),
 (3777, 2010),
 (15764, 2015),
 (4732, 2012),
 (4505, 2009),
 (7775, 2010),
 (10130, 2012),
 (1938, 2012),
 (895, 2004),
 (926, 2005),
 (4849, 2013),
 (6244, 2011),
 (1507, 2005),
 (1767, 2009),
 (4235, 2013),
 (3283, 2009),
 (11720, 2013),
 (921, 2004),
 (11762, 2016),
 (6230, 2008),
 (1437, 2003),
 (1091, 2007),
 (4806, 2017),
 (6895, 2014),
 (5551, 2012),
 (1298, 2003),
 (40, 2002),
 (4732, 2011),
 (1989, 2012),
 (1938, 2007),
 (5705, 2011),
 (233, 2004),
 (2072, 2011),
 (460, 2003),
 (4849, 2006),
 (3184, 2010),
 (1542, 2006),
 (1507, 2010),
 (3283, 2014),
 (921, 2013),
 (11423, 2013),
 (10131, 2012),
 (8360, 2008),
 (7731, 2013),
 (452, 2002),
 (13050, 2015),
 (773, 2005),
 (7853, 2013),
 (14107, 2015),
 (415, 2005),
 (40, 2009),
 (404, 2008),
 (1259, 2012),
 (5705, 2012),
 (586, 2002),
 (8048, 2012),
 (964, 2007),
 (225, 2013),
 (2646, 2012),
 (3990, 2016),
 (898, 2002),
 (219, 2008),
 (3642, 2006),
 (7448, 2010),
 (14457, 2017),
 (5279, 2016),
 (15423, 2015),
 (3193, 2006),
 (2047, 2013),
 (998, 2002),
 (3201, 2009),
 (2575, 2007),
 (34, 2002),
 (1172, 2005),
 (13048, 2012),
 (412, 2007),
 (4538, 2007),
 (705, 2002),
 (647, 2003),
 (976, 2011),
 (1660, 2004),
 (1228, 2007),
 (5350, 2010),
 (11530, 2015),
 (13164, 2017),
 (225, 2006),
 (10123, 2014),
 (4972, 2017),
 (1646, 2009),
 (11132, 2012),
 (4026, 2013),
 (8011, 2012),
 (4529, 2007),
 (1508, 2005),
 (475, 2004),
 (740, 2002),
 (10603, 2012),
 (2047, 2010),
 (4538, 2014),
 (305, 2006),
 (7531, 2017),
 (9895, 2015),
 (4732, 2016),
 (12730, 2014),
 (3254, 2017),
 (976, 2002),
 (594, 2004),
 (1994, 2015),
 (253, 2002),
 (668, 2006),
 (4972, 2008),
 (10197, 2014),
 (1931, 2007),
 (954, 2003),
 (510, 2008),
 (219, 2006),
 (3625, 2010),
 (3642, 2008),
 (3580, 2015),
 (188, 2002),
 (9111, 2014),
 (4020, 2009),
 (2155, 2014),
 (3815, 2011),
 (126, 2004),
 (6283, 2015),
 (106, 2003),
 (1157, 2009),
 (453, 2004),
 (6329, 2011),
 (4538, 2009),
 (8173, 2016),
 (1703, 2004),
 (1089, 2005),
 (1814, 2005),
 (5203, 2010),
 (1234, 2003),
 (1806, 2004),
 (4972, 2007),
 (1695, 2005),
 (5712, 2008),
 (962, 2010),
 (1303, 2012),
 (6432, 2009),
 (2717, 2016),
 (1514, 2005),
 (106, 2010),
 (837, 2006),
 (3551, 2009),
 (535, 2011),
 (164, 2004),
 (4930, 2011),
 (5279, 2015),
 (13074, 2017),
 (3543, 2009),
 (6249, 2009),
 (13431, 2014),
 (104, 2008),
 (7531, 2015),
 (8173, 2009),
 (2429, 2015),
 (801, 2011),
 (4538, 2016),
 (9901, 2011),
 (1325, 2002),
 (1701, 2011),
 (15873, 2017),
 (755, 2005),
 (6176, 2011),
 (1292, 2004),
 (10197, 2016),
 (962, 2005),
 (1076, 2004),
 (9129, 2013),
 (1303, 2005),
 (932, 2006),
 (6986, 2013),
 (1943, 2009),
 (8700, 2008),
 (434, 2007),
 (1688, 2003),
 (9029, 2015),
 (14444, 2017),
 (1772, 2010),
 (1529, 2008),
 (1118, 2015),
 (11713, 2013),
 (426, 2006),
 (7529, 2010),
 (815, 2006),
 (3137, 2009),
 (90, 2004),
 (12972, 2016),
 (3425, 2010),
 (755, 2010),
 (613, 2003),
 (13071, 2012),
 (8270, 2011),
 (944, 2010),
 (1076, 2003),
 (11132, 2016),
 (7441, 2010),
 (1303, 2002),
 (8700, 2007),
 (837, 2008),
 (4505, 2016),
 (2790, 2006),
 (3240, 2011),
 (542, 2002),
 (4567, 2008),
 (12804, 2015),
 (801, 2005),
 (150, 2011),
 (739, 2007),
 (6204, 2006),
 (12972, 2015),
 (7410, 2012),
 (8782, 2016),
 (4772, 2015),
 (12638, 2016),
 (1051, 2008),
 (9425, 2013),
 (1657, 2008),
 (4359, 2011),
 (9417, 2013),
 (13774, 2017),
 (1190, 2006),
 (8678, 2011),
 (9388, 2012),
 (4676, 2017),
 (3374, 2007),
 (6955, 2014),
 (569, 2002),
 (105, 2006),
 (823, 2004),
 (44, 2002),
 (2586, 2015),
 (150, 2002),
 (739, 2012),
 (1116, 2011),
 (4138, 2012),
 (3340, 2015),
 (5372, 2011),
 (1012, 2002),
 (8099, 2009),
 (1137, 2003),
 (6785, 2009),
 (9388, 2011),
 (571, 2005),
 (1620, 2008),
 (200, 2006),
 (11674, 2016),
 (7450, 2013),
 (3374, 2014),
 (9434, 2015),
 (840, 2002),
 (3254, 2015),
 (4366, 2007),
 (150, 2005),
 (3542, 2014),
 (1116, 2002),
 (512, 2009),
 (978, 2010),
 (10123, 2017),
 (4153, 2017),
 (4424, 2012),
 (15158, 2016),
 (1051, 2006),
 (2038, 2014),
 (2717, 2013),
 (46, 2003),
 (5702, 2016),
 (1137, 2004),
 (3374, 2017),
 (1131, 2003),
 (840, 2009),
 (4338, 2016),
 (3284, 2006),
 (833, 2007),
 (7059, 2010),
 (5106, 2011),
 (710, 2007),
 (978, 2005),
 (12703, 2014),
 (60, 2009),
 (375, 2009),
 (9918, 2010),
 (989, 2004),
 (5524, 2014),
 (18498, 2017),
 (2692, 2008),
 (4676, 2014),
 (3273, 2010),
 (666, 2005),
 (7738, 2013),
 (503, 2007),
 (517, 2008),
 (6893, 2011),
 (3284, 2013),
 (862, 2006),
 (13125, 2016),
 (512, 2007),
 (4270, 2012),
 (526, 2009),
 (1757, 2015),
 (9918, 2013),
 (8223, 2011),
 (13194, 2017),
 (5372, 2016),
 (7872, 2013),
 (2036, 2010),
 (3688, 2008),
 (9884, 2013),
 (199, 2011),
 (633, 2003),
 (1667, 2005),
 (232, 2004),
 (4222, 2008),
 (11428, 2014),
 (4662, 2014),
 (5842, 2009),
 (1451, 2012),
 (73, 2007),
 (10302, 2015),
 (1757, 2008),
 (2227, 2006),
 (6902, 2013),
 (147, 2005),
 (1056, 2005),
 (1277, 2004),
 (8779, 2012),
 (982, 2003),
 (1692, 2004),
 (7775, 2007),
 (633, 2004),
 (1667, 2010),
 (1571, 2007),
 (4371, 2011),
 (2233, 2016),
 (161, 2003),
 (6244, 2006),
 (4253, 2008),
 (1451, 2005),
 (715, 2002),
 (4772, 2017),
 (5231, 2010),
 (4897, 2015),
 (10954, 2015),
 (11423, 2017),
 (2159, 2007),
 (3830, 2011),
 (707, 2003),
 (1636, 2008),
 (10587, 2015),
 (1692, 2003),
 (16511, 2017),
 (8591, 2010),
 (1011, 2012),
 (4776, 2017),
 (7335, 2009),
 (1571, 2012),
 (4371, 2016),
 (926, 2003),
 (3990, 2012),
 (743, 2006),
 (161, 2004),
 (921, 2002),
 (12049, 2016),
 (110, 2005),
 (3200, 2014),
 (304, 2002),
 (3777, 2009),
 (4732, 2013),
 (5523, 2011),
 (6435, 2014),
 (12555, 2013),
 (7024, 2012),
 (10130, 2013),
 (7507, 2009),
 (491, 2003),
 (4849, 2012),
 (1507, 2004),
 (4235, 2012),
 (8268, 2009),
 (2859, 2013),
 (3283, 2008),
 (1767, 2008),
 (921, 2011),
 (1181, 2007),
 (137, 2002),
 (3547, 2015),
 (3200, 2005),
 (1437, 2002),
 (1091, 2006),
 (40, 2003),
 (2660, 2009),
 (328, 2002),
 (404, 2002),
 (11589, 2017),
 (1313, 2004),
 (5705, 2010),
 (15488, 2017),
 (7106, 2013),
 (5718, 2007),
 (8044, 2017),
 (2072, 2012),
 (1310, 2004),
 (225, 2011),
 (2646, 2010),
 (4849, 2005),
 (3184, 2011),
 (1507, 2013),
 (6632, 2011),
 (921, 2012),
 (11423, 2012),
 (10131, 2015),
 (15689, 2017),
 (452, 2003),
 (15514, 2015),
 (5099, 2007),
 (773, 2004),
 (10603, 2017),
 (5401, 2017),
 (3403, 2011),
 (14107, 2014),
 (415, 2004),
 (4422, 2006),
 (2047, 2007),
 (305, 2011),
 (404, 2009),
 (8214, 2007),
 (1077, 2006),
 (1259, 2015),
 (1428, 2004),
 (7015, 2008),
 (225, 2012),
 (6345, 2015),
 (1931, 2008),
 (3990, 2017),
 (855, 2003),
 (898, 2003),
 (219, 2011),
 (3642, 2007),
 (7448, 2011),
 (14457, 2016),
 (3201, 2008),
 (2575, 2006),
 (13048, 2013),
 (1118, 2016),
 (1172, 2006),
 (305, 2012),
 (34, 2003),
 (7541, 2013),
 (404, 2016),
 (1660, 2005),
 (976, 2012),
 (1428, 2003),
 (14168, 2017),
 (668, 2008),
 (225, 2005),
 (2735, 2006),
 (11132, 2013),
 (1598, 2004),
 (1245, 2015),
 (807, 2002),
 (510, 2006),
 (9460, 2013),
 (188, 2004),
 (4529, 2006),
 (7274, 2010),
 (3815, 2013),
 (6283, 2009),
 (10756, 2014),
 (740, 2003),
 (10603, 2015),
 (10310, 2017),
 (8753, 2017),
 (4538, 2015),
 (305, 2005),
 (7531, 2016),
 (1089, 2003),
 (2608, 2016),
 (4732, 2017),
 ...}